
###Problem Statement :
Replace all the tokens given in the (generic scheme)docx file according to a perticular company database by rendering data from a csv file.

Used Python and its necessary libraries to complete the task.

In [ ]:
#Installing python package to read documents
!pip install python-docx

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: python-docx in /usr/local/lib/python3.8/dist-packages (0.8.11)
Requirement already satisfied: lxml>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from python-docx) (4.9.2)

In [ ]:
#Importing All necessary libraries
import pandas as pd
import numpy as np
import docx
from docx import Document

In [ ]:
#Stored all the tokens in an Array
tokens = ['<Company Name>','<ESOP Plan Name>','<Board Meeting Date>','<Shareholder Meeting Date>','<Number of ESOPs>','<Maximum ESOP Percentage>','<Cliff Period>','<Vesting Maximum Period>','<Resignation Vested Exercise Period>','<Resignation Unvested  Exercise Period>','<Termination vested  Exercise Period>','<Termination Unvested Exercise Period>','<Jurisdiction>']

In [ ]:
#mounted csv file
path = "/content/drive/MyDrive/ESOP_database - Sheet1 (1).csv"

In [ ]:


data = pd.read_csv(path)
data.head()

,CompanyName,ESOP Plan Name,Board Meeting Date,Shareholder Meeting Date,Number of ESOPs,Maximum ESOP Percentage,Cliff Period,Vesting Maximum period,Resignation Vested Exercise Period,Resignation Unvested Exercise Period,Termination Vested Exercise Period,Termination Unvested Exercise Period,Jurisdiction
0,Boat,Boat ESOP Plan 2022,1 Jan 2022,1 Jan 2022,1000,5%,12 months,4 years,5 years,Cancelled,0 days,Cancelled,"Bangalore,India"
1,Locus,Locus ESOP Plan 2022,2 Feb 2022,2 Feb 2022,500,4%,11 months,3 years,4 years,Cancelled,0 days,Cancelled,"Mumbai,India"

In [ ]:
#Converted all the columns into tokens and setting company name as index column
data.columns = tokens
data_idx = data.set_index('<Company Name>')
data_idx.head()

,<ESOP Plan Name>,<Board Meeting Date>,<Shareholder Meeting Date>,<Number of ESOPs>,<Maximum ESOP Percentage>,<Cliff Period>,<Vesting Maximum Period>,<Resignation Vested Exercise Period>,<Resignation Unvested Exercise Period>,<Termination vested Exercise Period>,<Termination Unvested Exercise Period>,<Jurisdiction>
<Company Name>,,,,,,,,,,,,
Boat,Boat ESOP Plan 2022,1 Jan 2022,1 Jan 2022,1000,5%,12 months,4 years,5 years,Cancelled,0 days,Cancelled,"Bangalore,India"
Locus,Locus ESOP Plan 2022,2 Feb 2022,2 Feb 2022,500,4%,11 months,3 years,4 years,Cancelled,0 days,Cancelled,"Mumbai,India"

In [ ]:
#used iloc to select a perticular row or col from the dataset and selected comapny name to get its perticular data
Company_name = 'Boat'
idx = list(data_idx.index.values).index(Company_name)
comp_data = data.iloc[idx]
comp_data

<Company Name>                                            Boat
<ESOP Plan Name>                           Boat ESOP Plan 2022
<Board Meeting Date>                                1 Jan 2022
<Shareholder Meeting Date>                          1 Jan 2022
<Number of ESOPs>                                         1000
<Maximum ESOP Percentage>                                   5%
<Cliff Period>                                       12 months
<Vesting Maximum Period>                               4 years
<Resignation Vested Exercise Period>                   5 years
<Resignation Unvested  Exercise Period>              Cancelled
<Termination vested  Exercise Period>                   0 days
<Termination Unvested Exercise Period>               Cancelled
<Jurisdiction>                                 Bangalore,India
Name: 0, dtype: object

In [ ]:
# created a function to repalce tokens with perticular data 
def replace_string(doc,old_text,new_text):
  paragraphs = list(doc.paragraphs)
  for t in doc.tables:
      for row in t.rows:
          for cell in row.cells:
              for paragraph in cell.paragraphs:
                  paragraphs.append(paragraph)
  for p in paragraphs:
      if old_text in p.text:
          inline = p.runs
          # Loop added to work with runs (strings with same style)
          for i in range(len(inline)):
              if old_text in inline[i].text:
                  text = inline[i].text.replace(old_text, new_text)
                  inline[i].text = text

In [ ]:
filename = "/content/drive/MyDrive/Generic ESOP Scheme (1).docx"
doc = Document(filename)
file_new = (filename.split('.')[1])
for token in tokens:
  replace_string(doc,token,str(comp_data[token]))
doc.save('new.docx')